### ISSUE TITLE
Default installation is crashing with ERROR Unknown Request error: Probe Error: bad status code: 403 for an image request

### ISSUE THREAD

**Issue by ndbroadbent** [SNathJr/ghost-on-heroku#51]
Hello! I just deployed Ghost to Heroku, and I'm using the default setup with Cloudinary. I haven't made any changes to the repo.

I'm seeing this error in my logs:

```
2020-04-19T04:40:08.047310+00:00 app[web.1]: [2020-04-19 04:40:08] INFO "GET /ghost/" 200 54ms
2020-04-19T04:40:10.534456+00:00 app[web.1]: [2020-04-19 04:40:10] ERROR Unknown Request error.
2020-04-19T04:40:10.534468+00:00 app[web.1]:
2020-04-19T04:40:10.534496+00:00 app[web.1]: Unknown Request error.
2020-04-19T04:40:10.534498+00:00 app[web.1]:
2020-04-19T04:40:10.534501+00:00 app[web.1]: "https://static.ghost.org/v1.0.0/images/ghost-logo.svg"
2020-04-19T04:40:10.534501+00:00 app[web.1]:
2020-04-19T04:40:10.534502+00:00 app[web.1]: Error ID:
2020-04-19T04:40:10.534502+00:00 app[web.1]: da2a1e40-81f7-11ea-888a-b1044b0a2497
2020-04-19T04:40:10.534503+00:00 app[web.1]:
2020-04-19T04:40:10.534503+00:00 app[web.1]: Error Code:
2020-04-19T04:40:10.534503+00:00 app[web.1]: IMAGE_SIZE_URL
2020-04-19T04:40:10.534504+00:00 app[web.1]:
2020-04-19T04:40:10.534504+00:00 app[web.1]: ----------------------------------------
2020-04-19T04:40:10.534504+00:00 app[web.1]:
2020-04-19T04:40:10.534505+00:00 app[web.1]: InternalServerError: Unknown Request error.
2020-04-19T04:40:10.534506+00:00 app[web.1]: at new InternalServerError (/app/node_modules/ghost-ignition/lib/errors/index.js:77:23)
2020-04-19T04:40:10.534507+00:00 app[web.1]: at /app/node_modules/ghost/core/server/lib/image/image-size.js:175:31
2020-04-19T04:40:10.534507+00:00 app[web.1]: at tryCatcher (/app/node_modules/bluebird/js/release/util.js:16:23)
2020-04-19T04:40:10.534508+00:00 app[web.1]: at Promise._settlePromiseFromHandler (/app/node_modules/bluebird/js/release/promise.js:547:31)
2020-04-19T04:40:10.534508+00:00 app[web.1]: at Promise._settlePromise (/app/node_modules/bluebird/js/release/promise.js:604:18)
2020-04-19T04:40:10.534509+00:00 app[web.1]: at Promise._settlePromise0 (/app/node_modules/bluebird/js/release/promise.js:649:10)
2020-04-19T04:40:10.534509+00:00 app[web.1]: at Promise._settlePromises (/app/node_modules/bluebird/js/release/promise.js:725:18)
2020-04-19T04:40:10.534509+00:00 app[web.1]: at _drainQueueStep (/app/node_modules/bluebird/js/release/async.js:93:12)
2020-04-19T04:40:10.534510+00:00 app[web.1]: at _drainQueue (/app/node_modules/bluebird/js/release/async.js:86:9)
2020-04-19T04:40:10.534510+00:00 app[web.1]: at Async._drainQueues (/app/node_modules/bluebird/js/release/async.js:102:5)
2020-04-19T04:40:10.534511+00:00 app[web.1]: at Immediate.Async.drainQueues [as _onImmediate] (/app/node_modules/bluebird/js/release/async.js:15:14)
2020-04-19T04:40:10.534511+00:00 app[web.1]: at runCallback (timers.js:705:18)
2020-04-19T04:40:10.534511+00:00 app[web.1]: at tryOnImmediate (timers.js:676:5)
2020-04-19T04:40:10.534512+00:00 app[web.1]: at processImmediate (timers.js:658:5)
2020-04-19T04:40:10.534512+00:00 app[web.1]: at process.topLevelDomainCallback (domain.js:126:23)
2020-04-19T04:40:10.534513+00:00 app[web.1]:
2020-04-19T04:40:10.534513+00:00 app[web.1]: ProbeError: bad status code: 403
2020-04-19T04:40:10.534513+00:00 app[web.1]: at Request.<anonymous> (/app/node_modules/probe-image-size/http.js:46:19)
2020-04-19T04:40:10.534514+00:00 app[web.1]: at Request.emit (events.js:198:13)
2020-04-19T04:40:10.534514+00:00 app[web.1]: at Request.EventEmitter.emit (domain.js:448:20)
2020-04-19T04:40:10.534514+00:00 app[web.1]: at Request.onRequestResponse (/app/node_modules/request/request.js:1066:10)
2020-04-19T04:40:10.534515+00:00 app[web.1]: at ClientRequest.emit (events.js:203:15)
2020-04-19T04:40:10.534515+00:00 app[web.1]: at ClientRequest.EventEmitter.emit (domain.js:448:20)
2020-04-19T04:40:10.534516+00:00 app[web.1]: at HTTPParser.parserOnIncomingClient [as onIncoming] (_http_client.js:565:21)
2020-04-19T04:40:10.534516+00:00 app[web.1]: at HTTPParser.parserOnHeadersComplete (_http_common.js:111:17)
2020-04-19T04:40:10.534516+00:00 app[web.1]: at TLSSocket.socketOnData (_http_client.js:451:20)
2020-04-19T04:40:10.534517+00:00 app[web.1]: at TLSSocket.emit (events.js:198:13)
2020-04-19T04:40:10.534517+00:00 app[web.1]: at TLSSocket.EventEmitter.emit (domain.js:448:20)
2020-04-19T04:40:10.534517+00:00 app[web.1]: at addChunk (_stream_readable.js:288:12)
2020-04-19T04:40:10.534518+00:00 app[web.1]: at readableAddChunk (_stream_readable.js:269:11)
2020-04-19T04:40:10.534518+00:00 app[web.1]: at TLSSocket.Readable.push (_stream_readable.js:224:10)
2020-04-19T04:40:10.534519+00:00 app[web.1]: at TLSWrap.onStreamRead (internal/stream_base_commons.js:94:17)
2020-04-19T04:40:10.534519+00:00 app[web.1]:
```

Many of the requests seem to be timing out after 30 seconds because the server can't fetch the image at `https://static.ghost.org/v1.0.0/images/ghost-logo.svg`. Maybe a related issue: https://github.com/TryGhost/Ghost/issues/9231

I also tried upgrading my dynos to 1x Standard, but it's still happening.

Has anyone else run into this?

**Comment by JaneJeon** [comment]
Hmm, I don't think this issue has to do with our setup of Ghost. Rather, it seems like the Ghost team is just dismissing that problem.

I don't think there's anything we can do on our end; but, try contacting them/making a new issue so that they won't ignore the problem, and work things out with them. Once you get it resolved with the Ghost team, we'll close this issue.

**Comment by aayushdutt** [comment]
@ndbroadbent does the issue still persist? Could you please re-test it (just to make sure it wasn't some temporary issue with ghost)

**Comment by ndbroadbent** [comment]
Hi @aayushdutt, sorry I am no longer using Ghost on Heroku (I've switched to a server on Digital Ocean.) But I think I remember seeing the same error there, and also on my local machine, so I think it might just be an issue with Ghost in general. But anyway, I will close this issue now because I don't think it's related to this project!
